services:
  postgres:
    restart: 'no'

  lottery-app:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    image: lottery-backend-dev
    container_name: dev_lottery-app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/home/node/apps
      - lottery-node-modules:/home/node/apps/node_modules
      - lottery-pnpm-store:/home/node/apps/.pnpm-store
      - ~/.gitconfig:/root/.gitconfig:ro
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - DATABASE_HOST=postgres
    env_file:
      - .env
    ports:
      - '${LOTTERY_FORWARD_API_PORT:-3000}:${APP_PORT:-3000}'
    networks:
      - lottery-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  lottery-postgres-data:
    driver: local
  lottery-node-modules:
    driver: local
  lottery-pnpm-store:
    driver: local

networks:
  lottery-network:
    driver: bridge
